### ISSUE TITLE
on user logout seems does not logout or chat as offline status

### ISSUE THREAD

**Issue by mckaygerhard** [conversejs/roundcube-plugin#10]
hi, i recently do not note until some situactions where my buddies must poweroff their machines.. 

https://github.com/priyadi/roundcube-converse.js-xmpp-plugin/issues/11?_pjax=%23js-repo-pjax-container

seems the plugin does not go offline and in pdgin and other chats still appears as online!

this are solved in the repository plugin or still happened

i ask due **see that plugin still are in 3.X and converse are on 4.X, of course i prefer 3.X brand due works more with more browsers..**

**Comment by mckaygerhard** [comment]
i found a hack for this.. 
```
--- a/js/converse-rcmail.js
+++ b/js/converse-rcmail.js
@@ -41,6 +41,15 @@ function rcmail_converse_init(converse, args)
        }
     });
     
+       rcmail.addEventListener('beforeswitch-task', function(e){
+               if(e == 'logout'){
+                       converse.logout(); // reuse the logout of this auto plugin
+               }
+       });
+    
     //whitelist plugin, so converse doesn't refuse to load it
```

**Comment by drlight17** [comment]
old version issue. closed.

**Comment by mckaygerhard** [comment]
umm noted changes since #15 with commit 5b14f73919439533985c6f7a8c15c8d365b3c5c0  thanks i'll test later
