### ISSUE TITLE
Installed but cant get it working

### ISSUE THREAD

**Issue by ObaSensei** [conversejs/roundcube-plugin#11]
Hi, 
I have installed this over ssh and how do I get it to tie the IMAP user example@domain.com to the converse chat

**Comment by drlight17** [comment]
old version issue. closed.

**Comment by TCB13** [comment]
So... is it possible to use the IMAP login for login to a XMPP server?

**Comment by drlight17** [comment]
> So... is it possible to use the IMAP login for login to a XMPP server?

Yes. IMAP login and password will be used for auth to XMPP server.
