### ISSUE TITLE
hide groupchats list

### ISSUE THREAD

**Issue by roughnecks** [conversejs/roundcube-plugin#21]
Hello,

is there a way to hide that left column with list of groupchats? Since we have the main window with those I feel like it isn't needed after all and it wastes space on screen.

Thanks

**Comment by drlight17** [comment]
This is not a plugin feature, please check [converse.js config parametres](https://conversejs.org/docs/html/configuration.html). I believe that there is an option to do so. Parametres can be added in $rcmail_config['converse_config'] array in config.inc.php
Also, if you know some basics in css, you could check plugins/converse/css/custom.css - there you can add rule to hide anything from the converse.js app.

**Comment by roughnecks** [comment]
Well, in the web app there isn't anything like that, but I'll check.
