### ISSUE TITLE
no auto log on

### ISSUE THREAD

**Issue by joshp23** [conversejs/roundcube-plugin#5]
the converse window loads, however it does not log in automatically. Connection to bosh is set, I can log on manually. I have the following values in config:
```
// Hostname portion of XMPP username (bare JID), example: "example.net"
$rcmail_config['converse_xmpp_hostname']= function($args) {
	# return 'example.net';
	return preg_replace('/^.*@/', '', $args['user']);
	# return $args['host'];
};

// Username portion of XMPP username (bare JID), example: "user"
// if this contains @, this will only take the part before @,
// and the part after @ will replace the hostname definition above.
$rcmail_config['converse_xmpp_username']= function($args) {
	# return $args['user'];
	return preg_replace('/@.*$/', '', $args['user']);
};

// XMPP password
$rcmail_config['converse_xmpp_password']= function($args) {
	return $args['pass'];
};
```

**Comment by perseptron** [comment]
I have the same problem. Prosody said that user successfuly authenticated but converse still show login window

**Comment by alexandrelb** [comment]
I have the same. It seems the browser doesn't receive sid for retrieve BOSH session.

**Comment by ObaSensei** [comment]
How did you set it up to connect with BOSH?  Is it meant to connect the user automaticaly based on the domain or the user has to register?

**Comment by mckaygerhard** [comment]
i get a console erro in browser:

```
2022-07-15T00:58:58.594Z WARNING: attemptNonPreboundSession: Couldn't find credentials to log in with 
```

it seems the api of the conversejs changed but i cannot understand the stupid api documentation.. there's no stupid examples..

**Comment by mckaygerhard** [comment]
ok i found that the logic of the roundcube plugin its to emulate a plugin of the conversejs so the first developer created a conversejs js file .. that call the part that must to be upgraded.. i try to setup some settings and then test again..

**Comment by drlight17** [comment]
old version issue. closed.
