### ISSUE TITLE
please update installation and readme info about usage

### ISSUE THREAD

**Issue by mckaygerhard** [conversejs/roundcube-plugin#9]
i try several times to use newer versions of this plugin but unsusessfully..

if there's too complicated for us to update, tellme minimal info and i wirte proper README and send pull request PLEASE!!!!

**Comment by mckaygerhard** [comment]
if there's too complicated for you @devurandom , tellme minimal info and i wirte proper README and send pull request PLEASE!!!!

**Comment by drlight17** [comment]
old version issue. closed.

**Comment by mckaygerhard** [comment]
thansk for commit a22900ca4bf841c2ca85019cad76d51d58c3a63c
